/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicaodontologica;

import AccesosArchivo.AccesoAleatorioPaciente;
import AccesosArchivo.AccesoAleatorioDoctor;
import AccesosArchivo.AccesoAleatorioCita;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author William
 */
public class RevisionCita extends javax.swing.JFrame {
    int clic;

    /**
     * Creates new form RevisionCita
     */
    public RevisionCita() {
        initComponents();
        //listar();
        this.setLocationRelativeTo(null);
    }
    public void Ejemp(){
        SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");
        String Fecha= dFormat.format(JCita.getDate());
        JOptionPane.showMessageDialog(this, Fecha, "Notificación", JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    public void listar(){
        DefaultTableModel modelo=(DefaultTableModel)TablaCita.getModel();
        int a = TablaCita.getRowCount()-1;
        for(int i=a;i>=0;i--){
            modelo.removeRow(modelo.getRowCount()-1);
        }
        Object[] fila =new Object[10];
        try {
             SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");
            String Fecha= dFormat.format(JCita.getDate());
            AccesoAleatorioDoctor.crearFileDoctor( new File("Doctor.dat") );
            AccesoAleatorioPaciente.crearFilePaciente( new File("Paciente.dat") );
            AccesoAleatorioCita.crearFileCita( new File("Cita.dat") );
            for (int i = 0; i < AccesoAleatorioCita.getNumeroRegistros() ; i++) {
            Cita CM =AccesoAleatorioCita.getCita(i);
            if(CM.getActivo() && CM.getFecha().equals(Fecha)){
                fila[0]=CM.getCodigo().trim();
                fila[1]=CM.getCedulaP().trim();
                Paciente Pa =AccesoAleatorioPaciente.getPaciente(AccesoAleatorioPaciente.buscarRegistroC(CM.getCedulaP().trim()));
                fila[2]=Pa.getNombre()+" "+Pa.getApellido();
                fila[3]=Pa.getTelefono().trim();
                fila[4]=CM.getMotivo().trim();
                fila[5]=CM.getUsuarioD().trim();
                Doctor D =AccesoAleatorioDoctor.getDoctor(AccesoAleatorioDoctor.buscarRegistroID(CM.getUsuarioD().trim()));
                fila[6]=D.getNombre()+" "+D.getApellido();
                fila[7]=D.getEspecialidad().trim();
                fila[8]=CM.getFecha();
                fila[9]=CM.getHora();
                
            
                modelo.addRow(fila);
                TablaCita.setModel(modelo);
            }
            }
            RowSorter<TableModel> sorter = new TableRowSorter<>(modelo);
            TablaCita.setRowSorter(sorter);
            AccesoAleatorioPaciente.cerrar();
            AccesoAleatorioDoctor.cerrar();
            AccesoAleatorioCita.cerrar();
            
        } catch (IOException ex) {
            Logger.getLogger(RegistroD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCita = new javax.swing.JTable();
        JCita = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Revision Citas");
        setMinimumSize(new java.awt.Dimension(950, 400));
        setPreferredSize(new java.awt.Dimension(1300, 500));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("CITAS REGISTRADAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 13, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(900, 300));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 300));

        TablaCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Cita", "C.I. Paciente", "Nombre Paciente", "Telefono Paciente", "Motivo", "Codigo Medico", "Nombre Medico", "Especialidad", "Fecha", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCita);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        JCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCitaMouseClicked(evt);
            }
        });
        JCita.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JCitaPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 100);
        jPanel1.add(JCita, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCitaMouseClicked

        
    }//GEN-LAST:event_TablaCitaMouseClicked

    private void JCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCitaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCitaMouseClicked

    private void JCitaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JCitaPropertyChange
        // TODO add your handling code here:
        listar();
        //Ejemp();
    }//GEN-LAST:event_JCitaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevisionCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar JCita;
    private javax.swing.JTable TablaCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
